#pipeline
#install.packages("devtools")
#install.packages("ape","readxl","thematic","flexsurv","ggforestplot","phytools","brms", "phylolm")
library("readxl")
library("dplyr")
library("survival")
library("ggplot2")
library("survminer")
library("thematic")
library("flexsurv")
library("ggrepel")
library("phytools")
library("brms")
library("rstan")
library("MASS")
library("nlme")

library("ggforestplot")
#remotes::install_github("JosephCrispell/basicPlotteR")
library("basicPlotteR")

## (this just globally sets the ggplot2 theme to theme_bw) 
ggplot2::theme_set(ggplot2::theme_bw(base_size = 16)) 

setwd("/Users/eugene/Projects/github/PrimateLongevityGitHub/")
source("load_data.R")
source("support_functions.R")
source("construct_lifetables.R")
source("primate_tree_bootstap.R");
source("plot_survival_hazard_estimates.R")
source("lifetable_regression_brms.R")
source("gompertzFitLogLikUnion.R");
source("aging_parameters_forest_plot.R")
source("phylo_regression_ancestal_states.R")
source("bayesian_body_weight.R")
source("power_sim2.R")
